<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>47</x>
			<y>43</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>75</x>
			<y>43</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>104</x>
			<y>43</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>132</x>
			<y>43</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>160</x>
			<y>43</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>188</x>
			<y>43</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>216</x>
			<y>43</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>1347</x>
			<y>297</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>244</x>
			<y>43</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>283</x>
			<y>44</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>311</x>
			<y>43</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>339</x>
			<y>43</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>367</x>
			<y>43</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>396</x>
			<y>44</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>426</x>
			<y>43</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>1347</x>
			<y>384</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>454</x>
			<y>43</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>479</x>
			<y>42</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>518</x>
			<y>43</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>43</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>575</x>
			<y>43</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>601</x>
			<y>42</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>632</x>
			<y>43</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>1347</x>
			<y>489</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>49</x>
			<y>70</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>77</x>
			<y>71</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>102</x>
			<y>69</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>132</x>
			<y>69</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>161</x>
			<y>70</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>187</x>
			<y>69</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>215</x>
			<y>68</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>1347</x>
			<y>576</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>243</x>
			<y>69</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>282</x>
			<y>70</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>310</x>
			<y>71</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>342</x>
			<y>70</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>368</x>
			<y>68</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>398</x>
			<y>71</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>425</x>
			<y>70</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>1347</x>
			<y>663</y>
		</node>
	</nodes>
</root>

