<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>514</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>85</x>
			<y>16</y>
		</node>
		<node>
			<index>642</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>85</x>
			<y>48</y>
		</node>
		<node>
			<index>770</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>108</x>
			<y>16</y>
		</node>
		<node>
			<index>898</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>110</x>
			<y>47</y>
		</node>
		<node>
			<index>1026</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>135</x>
			<y>16</y>
		</node>
		<node>
			<index>1154</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>134</x>
			<y>47</y>
		</node>
		<node>
			<index>1282</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>159</x>
			<y>16</y>
		</node>
		<node>
			<index>1410</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>160</x>
			<y>47</y>
		</node>
		<node>
			<index>1538</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>222</x>
			<y>16</y>
		</node>
		<node>
			<index>1666</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>222</x>
			<y>47</y>
		</node>
		<node>
			<index>1794</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>247</x>
			<y>16</y>
		</node>
		<node>
			<index>1922</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>248</x>
			<y>46</y>
		</node>
		<node>
			<index>2050</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>272</x>
			<y>17</y>
		</node>
		<node>
			<index>2178</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>273</x>
			<y>46</y>
		</node>
		<node>
			<index>2306</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>298</x>
			<y>17</y>
		</node>
		<node>
			<index>2434</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>298</x>
			<y>48</y>
		</node>
		<node>
			<index>2561</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>555</x>
			<y>45</y>
		</node>
		<node>
			<index>2689</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>595</x>
			<y>45</y>
		</node>
	</nodes>
</root>

