<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>175</x>
			<y>314</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>256</x>
			<y>313</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>184</x>
			<y>474</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>270</x>
			<y>475</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>357</x>
			<y>476</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>445</x>
			<y>476</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>536</x>
			<y>477</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>624</x>
			<y>477</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>132</x>
			<y>622</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>132</x>
			<y>647</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>157</x>
			<y>623</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>159</x>
			<y>647</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>182</x>
			<y>624</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>182</x>
			<y>649</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>206</x>
			<y>625</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>206</x>
			<y>649</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>230</x>
			<y>623</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>230</x>
			<y>649</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>253</x>
			<y>624</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>254</x>
			<y>649</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>276</x>
			<y>625</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>278</x>
			<y>648</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>302</x>
			<y>625</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>302</x>
			<y>649</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>625</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>326</x>
			<y>648</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>351</x>
			<y>625</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>351</x>
			<y>648</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>373</x>
			<y>625</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>373</x>
			<y>648</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>398</x>
			<y>625</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>398</x>
			<y>649</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>422</x>
			<y>623</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>422</x>
			<y>648</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>446</x>
			<y>623</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>446</x>
			<y>646</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>470</x>
			<y>624</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>470</x>
			<y>646</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>495</x>
			<y>624</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>495</x>
			<y>648</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>520</x>
			<y>624</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>520</x>
			<y>648</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>542</x>
			<y>624</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>543</x>
			<y>647</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>566</x>
			<y>623</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>566</x>
			<y>646</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>590</x>
			<y>622</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>591</x>
			<y>646</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>615</x>
			<y>623</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>616</x>
			<y>648</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>640</x>
			<y>625</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>641</x>
			<y>648</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>663</x>
			<y>623</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>663</x>
			<y>650</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>687</x>
			<y>622</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>687</x>
			<y>647</y>
		</node>
	</nodes>
</root>

