<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>108</x>
			<y>27</y>
		</node>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>108</x>
			<y>49</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>135</x>
			<y>26</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>135</x>
			<y>48</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>163</x>
			<y>27</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>163</x>
			<y>49</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>190</x>
			<y>27</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>190</x>
			<y>48</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>218</x>
			<y>27</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>218</x>
			<y>49</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>245</x>
			<y>27</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>245</x>
			<y>49</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>273</x>
			<y>27</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>273</x>
			<y>48</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>300</x>
			<y>27</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>300</x>
			<y>48</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>346</x>
			<y>27</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>346</x>
			<y>49</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>374</x>
			<y>27</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>374</x>
			<y>49</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>401</x>
			<y>27</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>401</x>
			<y>49</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>429</x>
			<y>26</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>429</x>
			<y>49</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>456</x>
			<y>27</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>456</x>
			<y>48</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>483</x>
			<y>26</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>483</x>
			<y>48</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>511</x>
			<y>27</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>511</x>
			<y>48</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>539</x>
			<y>26</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>539</x>
			<y>48</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>585</x>
			<y>26</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>585</x>
			<y>49</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>612</x>
			<y>26</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>613</x>
			<y>49</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>640</x>
			<y>27</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>640</x>
			<y>49</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>667</x>
			<y>27</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>667</x>
			<y>49</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>695</x>
			<y>27</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>695</x>
			<y>49</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>722</x>
			<y>27</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>722</x>
			<y>49</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>750</x>
			<y>27</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>750</x>
			<y>49</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>776</x>
			<y>27</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>777</x>
			<y>49</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>920</x>
			<y>29</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>921</x>
			<y>63</y>
		</node>
	</nodes>
</root>

