<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>62</x>
			<y>62</y>
		</node>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>61</x>
			<y>36</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>62</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>89</x>
			<y>36</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>117</x>
			<y>62</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>117</x>
			<y>36</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>145</x>
			<y>62</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>145</x>
			<y>37</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>172</x>
			<y>62</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>173</x>
			<y>36</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>202</x>
			<y>62</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>202</x>
			<y>37</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>229</x>
			<y>62</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>229</x>
			<y>36</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>257</x>
			<y>61</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>258</x>
			<y>35</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>295</x>
			<y>62</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>295</x>
			<y>35</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>324</x>
			<y>62</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>324</x>
			<y>37</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>352</x>
			<y>61</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>352</x>
			<y>35</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>380</x>
			<y>62</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>381</x>
			<y>37</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>407</x>
			<y>61</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>407</x>
			<y>36</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>437</x>
			<y>62</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>437</x>
			<y>37</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>463</x>
			<y>61</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>463</x>
			<y>36</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>492</x>
			<y>61</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>492</x>
			<y>36</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>531</x>
			<y>61</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>531</x>
			<y>36</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>559</x>
			<y>62</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>559</x>
			<y>37</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>587</x>
			<y>62</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>588</x>
			<y>36</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>615</x>
			<y>62</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>615</x>
			<y>36</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>644</x>
			<y>62</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>644</x>
			<y>36</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>672</x>
			<y>62</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>672</x>
			<y>36</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>699</x>
			<y>62</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>698</x>
			<y>37</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>726</x>
			<y>62</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>728</x>
			<y>37</y>
		</node>
	</nodes>
</root>

