<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>4227626</index>
			<img>image/up_up_green.gif</img>
			<direction>2</direction>
			<x>64</x>
			<y>82</y>
		</node>
		<node>
			<index>4227634</index>
			<img>image/up_up_green.gif</img>
			<direction>1</direction>
			<x>63</x>
			<y>56</y>
		</node>
		<node>
			<index>4227642</index>
			<img>image/up_up_green.gif</img>
			<direction>2</direction>
			<x>92</x>
			<y>82</y>
		</node>
		<node>
			<index>4227650</index>
			<img>image/up_up_green.gif</img>
			<direction>1</direction>
			<x>91</x>
			<y>56</y>
		</node>
		<node>
			<index>4227658</index>
			<img>image/up_up_green.gif</img>
			<direction>2</direction>
			<x>120</x>
			<y>82</y>
		</node>
		<node>
			<index>4227666</index>
			<img>image/up_up_green.gif</img>
			<direction>1</direction>
			<x>119</x>
			<y>56</y>
		</node>
		<node>
			<index>4227674</index>
			<img>image/up_up_green.gif</img>
			<direction>2</direction>
			<x>148</x>
			<y>82</y>
		</node>
		<node>
			<index>4227682</index>
			<img>image/up_up_green.gif</img>
			<direction>1</direction>
			<x>147</x>
			<y>56</y>
		</node>
		<node>
			<index>4227690</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>176</x>
			<y>82</y>
		</node>
		<node>
			<index>4227698</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>175</x>
			<y>56</y>
		</node>
		<node>
			<index>4227706</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>204</x>
			<y>82</y>
		</node>
		<node>
			<index>4227714</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>203</x>
			<y>56</y>
		</node>
		<node>
			<index>4227722</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>232</x>
			<y>82</y>
		</node>
		<node>
			<index>4227730</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>231</x>
			<y>56</y>
		</node>
		<node>
			<index>4227738</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>260</x>
			<y>82</y>
		</node>
		<node>
			<index>4227746</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>259</x>
			<y>56</y>
		</node>
		<node>
			<index>4227754</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>299</x>
			<y>82</y>
		</node>
		<node>
			<index>4227762</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>298</x>
			<y>56</y>
		</node>
		<node>
			<index>4227770</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>327</x>
			<y>82</y>
		</node>
		<node>
			<index>4227778</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>56</y>
		</node>
		<node>
			<index>4227786</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>355</x>
			<y>82</y>
		</node>
		<node>
			<index>4227794</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>354</x>
			<y>56</y>
		</node>
		<node>
			<index>4227802</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>383</x>
			<y>82</y>
		</node>
		<node>
			<index>4227810</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>382</x>
			<y>56</y>
		</node>
		<node>
			<index>4227818</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>411</x>
			<y>82</y>
		</node>
		<node>
			<index>4227826</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>410</x>
			<y>56</y>
		</node>
		<node>
			<index>4227834</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>439</x>
			<y>82</y>
		</node>
		<node>
			<index>4227842</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>438</x>
			<y>56</y>
		</node>
		<node>
			<index>4227850</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>467</x>
			<y>82</y>
		</node>
		<node>
			<index>4227858</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>466</x>
			<y>56</y>
		</node>
		<node>
			<index>4227866</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>495</x>
			<y>82</y>
		</node>
		<node>
			<index>4227874</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>494</x>
			<y>56</y>
		</node>
		<node>
			<index>4227882</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>534</x>
			<y>82</y>
		</node>
		<node>
			<index>4227890</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>533</x>
			<y>56</y>
		</node>
		<node>
			<index>4227898</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>562</x>
			<y>82</y>
		</node>
		<node>
			<index>4227906</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>561</x>
			<y>56</y>
		</node>
		<node>
			<index>4227914</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>590</x>
			<y>82</y>
		</node>
		<node>
			<index>4227922</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>589</x>
			<y>56</y>
		</node>
		<node>
			<index>4227930</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>618</x>
			<y>82</y>
		</node>
		<node>
			<index>4227938</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>617</x>
			<y>56</y>
		</node>
		<node>
			<index>4227946</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>646</x>
			<y>82</y>
		</node>
		<node>
			<index>4227954</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>645</x>
			<y>56</y>
		</node>
		<node>
			<index>4227962</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>674</x>
			<y>82</y>
		</node>
		<node>
			<index>4227970</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>673</x>
			<y>56</y>
		</node>
		<node>
			<index>4227978</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>702</x>
			<y>82</y>
		</node>
		<node>
			<index>4227986</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>701</x>
			<y>56</y>
		</node>
		<node>
			<index>4227994</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>730</x>
			<y>82</y>
		</node>
		<node>
			<index>4228002</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>729</x>
			<y>56</y>
		</node>
		<node>
			<index>4228041</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>773</x>
			<y>94</y>
		</node>
		<node>
			<index>4228049</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>818</x>
			<y>94</y>
		</node>
		<node>
			<index>4228057</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>864</x>
			<y>92</y>
		</node>
		<node>
			<index>4228065</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>909</x>
			<y>95</y>
		</node>
	</nodes>
</root>

