<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>105</x>
			<y>259</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>105</x>
			<y>284</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>105</x>
			<y>314</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>105</x>
			<y>337</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>129</x>
			<y>314</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>129</x>
			<y>337</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>153</x>
			<y>314</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>153</x>
			<y>337</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>177</x>
			<y>314</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>177</x>
			<y>337</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>202</x>
			<y>314</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>202</x>
			<y>337</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>227</x>
			<y>314</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>227</x>
			<y>337</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>252</x>
			<y>314</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>252</x>
			<y>337</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>277</x>
			<y>314</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>277</x>
			<y>337</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>301</x>
			<y>314</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>301</x>
			<y>337</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>314</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>326</x>
			<y>337</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>350</x>
			<y>314</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>350</x>
			<y>337</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>375</x>
			<y>314</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>375</x>
			<y>337</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>400</x>
			<y>314</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>400</x>
			<y>337</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>424</x>
			<y>314</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>424</x>
			<y>337</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>448</x>
			<y>314</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>448</x>
			<y>337</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>472</x>
			<y>314</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>472</x>
			<y>337</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>496</x>
			<y>314</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>496</x>
			<y>337</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>519</x>
			<y>314</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>519</x>
			<y>337</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>542</x>
			<y>314</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>542</x>
			<y>337</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>566</x>
			<y>314</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>566</x>
			<y>337</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>590</x>
			<y>314</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>590</x>
			<y>337</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>614</x>
			<y>314</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>614</x>
			<y>337</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>638</x>
			<y>314</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>638</x>
			<y>337</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>662</x>
			<y>314</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>662</x>
			<y>337</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>105</x>
			<y>369</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>105</x>
			<y>392</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>129</x>
			<y>369</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>129</x>
			<y>392</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>153</x>
			<y>369</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>153</x>
			<y>392</y>
		</node>
	</nodes>
</root>

