<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>10001</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>111</x>
			<y>53</y>
		</node>
		<node>
			<index>10002</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>111</x>
			<y>72</y>
		</node>
		<node>
			<index>10003</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>136</x>
			<y>52</y>
		</node>
		<node>
			<index>10004</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>136</x>
			<y>73</y>
		</node>
		<node>
			<index>10005</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>161</x>
			<y>52</y>
		</node>
		<node>
			<index>10006</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>161</x>
			<y>74</y>
		</node>
		<node>
			<index>10007</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>186</x>
			<y>52</y>
		</node>
		<node>
			<index>10008</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>186</x>
			<y>73</y>
		</node>
		<node>
			<index>10009</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>211</x>
			<y>52</y>
		</node>
		<node>
			<index>10010</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>210</x>
			<y>74</y>
		</node>
		<node>
			<index>10011</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>236</x>
			<y>52</y>
		</node>
		<node>
			<index>10012</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>236</x>
			<y>73</y>
		</node>
		<node>
			<index>10013</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>315</x>
			<y>52</y>
		</node>
		<node>
			<index>10014</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>315</x>
			<y>74</y>
		</node>
		<node>
			<index>10015</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>341</x>
			<y>52</y>
		</node>
		<node>
			<index>10016</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>340</x>
			<y>73</y>
		</node>
		<node>
			<index>10017</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>366</x>
			<y>52</y>
		</node>
		<node>
			<index>10018</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>366</x>
			<y>74</y>
		</node>
		<node>
			<index>10019</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>391</x>
			<y>52</y>
		</node>
		<node>
			<index>10020</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>391</x>
			<y>74</y>
		</node>
		<node>
			<index>10021</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>416</x>
			<y>52</y>
		</node>
		<node>
			<index>10022</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>416</x>
			<y>74</y>
		</node>
		<node>
			<index>10023</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>441</x>
			<y>52</y>
		</node>
		<node>
			<index>10024</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>441</x>
			<y>73</y>
		</node>
		<node>
			<index>10101</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>538</x>
			<y>71</y>
		</node>
		<node>
			<index>10102</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>563</x>
			<y>71</y>
		</node>
	</nodes>
</root>

