<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>10001</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>74</x>
			<y>30</y>
		</node>
		<node>
			<index>10002</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>74</x>
			<y>64</y>
		</node>
		<node>
			<index>10003</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>103</x>
			<y>30</y>
		</node>
		<node>
			<index>10004</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>103</x>
			<y>64</y>
		</node>
		<node>
			<index>10005</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>133</x>
			<y>30</y>
		</node>
		<node>
			<index>10006</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>133</x>
			<y>64</y>
		</node>
		<node>
			<index>10007</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>163</x>
			<y>30</y>
		</node>
		<node>
			<index>10008</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>163</x>
			<y>64</y>
		</node>
		<node>
			<index>10009</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>192</x>
			<y>30</y>
		</node>
		<node>
			<index>10010</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>192</x>
			<y>64</y>
		</node>
		<node>
			<index>10011</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>222</x>
			<y>30</y>
		</node>
		<node>
			<index>10012</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>222</x>
			<y>64</y>
		</node>
		<node>
			<index>10013</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>252</x>
			<y>30</y>
		</node>
		<node>
			<index>10014</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>252</x>
			<y>64</y>
		</node>
		<node>
			<index>10015</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>280</x>
			<y>30</y>
		</node>
		<node>
			<index>10016</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>281</x>
			<y>64</y>
		</node>
		<node>
			<index>10017</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>30</y>
		</node>
		<node>
			<index>10018</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>326</x>
			<y>64</y>
		</node>
		<node>
			<index>10019</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>356</x>
			<y>30</y>
		</node>
		<node>
			<index>10020</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>356</x>
			<y>64</y>
		</node>
		<node>
			<index>10021</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>386</x>
			<y>30</y>
		</node>
		<node>
			<index>10022</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>386</x>
			<y>64</y>
		</node>
		<node>
			<index>10023</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>415</x>
			<y>30</y>
		</node>
		<node>
			<index>10024</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>415</x>
			<y>64</y>
		</node>
		<node>
			<index>10025</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>445</x>
			<y>30</y>
		</node>
		<node>
			<index>10026</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>445</x>
			<y>64</y>
		</node>
		<node>
			<index>10027</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>474</x>
			<y>30</y>
		</node>
		<node>
			<index>10028</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>474</x>
			<y>64</y>
		</node>
		<node>
			<index>10029</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>504</x>
			<y>30</y>
		</node>
		<node>
			<index>10030</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>503</x>
			<y>64</y>
		</node>
		<node>
			<index>10031</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>533</x>
			<y>30</y>
		</node>
		<node>
			<index>10032</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>534</x>
			<y>64</y>
		</node>
		<node>
			<index>10033</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>579</x>
			<y>31</y>
		</node>
		<node>
			<index>10034</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>579</x>
			<y>64</y>
		</node>
		<node>
			<index>10035</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>608</x>
			<y>31</y>
		</node>
		<node>
			<index>10036</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>608</x>
			<y>64</y>
		</node>
		<node>
			<index>10037</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>638</x>
			<y>31</y>
		</node>
		<node>
			<index>10038</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>638</x>
			<y>64</y>
		</node>
		<node>
			<index>10039</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>668</x>
			<y>31</y>
		</node>
		<node>
			<index>10040</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>668</x>
			<y>64</y>
		</node>
		<node>
			<index>10041</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>697</x>
			<y>31</y>
		</node>
		<node>
			<index>10042</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>697</x>
			<y>64</y>
		</node>
		<node>
			<index>10043</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>727</x>
			<y>31</y>
		</node>
		<node>
			<index>10044</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>727</x>
			<y>64</y>
		</node>
		<node>
			<index>10045</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>757</x>
			<y>31</y>
		</node>
		<node>
			<index>10046</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>757</x>
			<y>64</y>
		</node>
		<node>
			<index>10047</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>786</x>
			<y>31</y>
		</node>
		<node>
			<index>10048</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>786</x>
			<y>64</y>
		</node>
		<node>
			<index>10101</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>847</x>
			<y>20</y>
		</node>
		<node>
			<index>10102</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>912</x>
			<y>19</y>
		</node>
		<node>
			<index>10103</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>847</x>
			<y>57</y>
		</node>
		<node>
			<index>10104</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>912</x>
			<y>57</y>
		</node>
	</nodes>
</root>

