<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>90</x>
			<y>176</y>
		</node>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>206</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>114</x>
			<y>176</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>114</x>
			<y>206</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>137</x>
			<y>176</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>138</x>
			<y>206</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>161</x>
			<y>176</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>162</x>
			<y>206</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>185</x>
			<y>176</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>185</x>
			<y>206</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>209</x>
			<y>176</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>209</x>
			<y>206</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>232</x>
			<y>176</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>232</x>
			<y>206</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>255</x>
			<y>176</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>255</x>
			<y>206</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>279</x>
			<y>176</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>279</x>
			<y>206</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>303</x>
			<y>176</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>303</x>
			<y>206</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>327</x>
			<y>176</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>327</x>
			<y>206</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>351</x>
			<y>176</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>351</x>
			<y>206</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>89</x>
			<y>234</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>266</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>113</x>
			<y>234</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>113</x>
			<y>266</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>137</x>
			<y>234</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>137</x>
			<y>266</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>161</x>
			<y>234</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>161</x>
			<y>266</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>185</x>
			<y>234</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>185</x>
			<y>266</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>209</x>
			<y>234</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>209</x>
			<y>266</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>233</x>
			<y>234</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>233</x>
			<y>266</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>257</x>
			<y>234</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>257</x>
			<y>266</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>281</x>
			<y>234</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>281</x>
			<y>266</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>305</x>
			<y>234</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>305</x>
			<y>266</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>329</x>
			<y>234</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>329</x>
			<y>266</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>353</x>
			<y>234</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>353</x>
			<y>266</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>377</x>
			<y>234</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>377</x>
			<y>266</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>401</x>
			<y>234</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>401</x>
			<y>266</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>425</x>
			<y>234</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>425</x>
			<y>266</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>449</x>
			<y>234</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>449</x>
			<y>266</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>473</x>
			<y>234</y>
		</node>
		<node>
			<index>58</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>473</x>
			<y>266</y>
		</node>
		<node>
			<index>59</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>497</x>
			<y>234</y>
		</node>
		<node>
			<index>60</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>497</x>
			<y>266</y>
		</node>
		<node>
			<index>61</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>521</x>
			<y>234</y>
		</node>
		<node>
			<index>62</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>521</x>
			<y>266</y>
		</node>
		<node>
			<index>63</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>234</y>
		</node>
		<node>
			<index>64</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>545</x>
			<y>266</y>
		</node>
		<node>
			<index>65</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>569</x>
			<y>234</y>
		</node>
		<node>
			<index>66</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>569</x>
			<y>266</y>
		</node>
		<node>
			<index>67</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>593</x>
			<y>234</y>
		</node>
		<node>
			<index>68</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>593</x>
			<y>266</y>
		</node>
		<node>
			<index>69</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>617</x>
			<y>234</y>
		</node>
		<node>
			<index>70</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>617</x>
			<y>266</y>
		</node>
		<node>
			<index>71</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>641</x>
			<y>234</y>
		</node>
		<node>
			<index>72</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>641</x>
			<y>266</y>
		</node>
		<node>
			<index>73</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>89</x>
			<y>295</y>
		</node>
		<node>
			<index>74</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>327</y>
		</node>
		<node>
			<index>75</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>90</x>
			<y>416</y>
		</node>
		<node>
			<index>76</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>90</x>
			<y>447</y>
		</node>
		<node>
			<index>77</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>114</x>
			<y>416</y>
		</node>
		<node>
			<index>78</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>114</x>
			<y>447</y>
		</node>
		<node>
			<index>79</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>138</x>
			<y>416</y>
		</node>
		<node>
			<index>80</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>138</x>
			<y>447</y>
		</node>
		<node>
			<index>81</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>162</x>
			<y>416</y>
		</node>
		<node>
			<index>82</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>162</x>
			<y>447</y>
		</node>
		<node>
			<index>83</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>89</x>
			<y>475</y>
		</node>
		<node>
			<index>84</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>507</y>
		</node>
		<node>
			<index>85</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>113</x>
			<y>475</y>
		</node>
		<node>
			<index>86</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>113</x>
			<y>507</y>
		</node>
		<node>
			<index>87</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>137</x>
			<y>475</y>
		</node>
		<node>
			<index>88</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>137</x>
			<y>507</y>
		</node>
		<node>
			<index>89</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>161</x>
			<y>475</y>
		</node>
		<node>
			<index>90</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>161</x>
			<y>507</y>
		</node>
	</nodes>
</root>

