<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>165</x>
			<y>204</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>236</x>
			<y>203</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>658</x>
			<y>203</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>688</x>
			<y>203</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>118</x>
			<y>313</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>118</x>
			<y>335</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>146</x>
			<y>313</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>146</x>
			<y>335</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>173</x>
			<y>313</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>173</x>
			<y>335</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>200</x>
			<y>313</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>200</x>
			<y>335</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>226</x>
			<y>313</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>226</x>
			<y>335</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>252</x>
			<y>313</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>252</x>
			<y>335</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>289</x>
			<y>312</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>289</x>
			<y>334</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>317</x>
			<y>312</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>317</x>
			<y>334</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>343</x>
			<y>312</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>343</x>
			<y>334</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>370</x>
			<y>312</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>370</x>
			<y>334</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>396</x>
			<y>312</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>396</x>
			<y>334</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>422</x>
			<y>312</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>422</x>
			<y>334</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>459</x>
			<y>312</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>459</x>
			<y>334</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>486</x>
			<y>312</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>486</x>
			<y>334</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>513</x>
			<y>312</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>513</x>
			<y>334</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>539</x>
			<y>312</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>539</x>
			<y>334</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>566</x>
			<y>312</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>566</x>
			<y>334</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>592</x>
			<y>312</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>592</x>
			<y>334</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>630</x>
			<y>312</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>630</x>
			<y>333</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>657</x>
			<y>312</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>657</x>
			<y>333</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>684</x>
			<y>312</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>684</x>
			<y>333</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>710</x>
			<y>312</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>710</x>
			<y>333</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>737</x>
			<y>312</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>737</x>
			<y>333</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>764</x>
			<y>312</y>
		</node>
		<node>
			<index>58</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>764</x>
			<y>333</y>
		</node>
	</nodes>
</root>

