<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>141</x>
			<y>43</y>
		</node>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>165</x>
			<y>43</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>188</x>
			<y>43</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>212</x>
			<y>43</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>236</x>
			<y>43</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>260</x>
			<y>43</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>284</x>
			<y>43</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>308</x>
			<y>43</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>332</x>
			<y>43</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>355</x>
			<y>43</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>378</x>
			<y>43</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>401</x>
			<y>43</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>425</x>
			<y>43</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>449</x>
			<y>43</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>473</x>
			<y>43</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>497</x>
			<y>43</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>521</x>
			<y>43</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>43</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>569</x>
			<y>43</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>593</x>
			<y>43</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>617</x>
			<y>43</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>640</x>
			<y>43</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>663</x>
			<y>43</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>687</x>
			<y>43</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>133</x>
			<y>104</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>133</x>
			<y>126</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>157</x>
			<y>104</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>157</x>
			<y>127</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>181</x>
			<y>104</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>182</x>
			<y>128</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>205</x>
			<y>105</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>204</x>
			<y>129</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>229</x>
			<y>105</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>230</x>
			<y>129</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>253</x>
			<y>106</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>253</x>
			<y>129</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>278</x>
			<y>105</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>279</x>
			<y>129</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>301</x>
			<y>105</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>302</x>
			<y>128</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>105</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>326</x>
			<y>129</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>350</x>
			<y>104</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>351</x>
			<y>129</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>374</x>
			<y>104</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>374</x>
			<y>129</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>398</x>
			<y>104</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>398</x>
			<y>129</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>423</x>
			<y>105</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>423</x>
			<y>129</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>447</x>
			<y>105</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>448</x>
			<y>127</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>470</x>
			<y>105</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>470</x>
			<y>129</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>495</x>
			<y>105</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>496</x>
			<y>128</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>520</x>
			<y>106</y>
		</node>
		<node>
			<index>58</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>521</x>
			<y>129</y>
		</node>
		<node>
			<index>59</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>544</x>
			<y>104</y>
		</node>
		<node>
			<index>60</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>543</x>
			<y>128</y>
		</node>
		<node>
			<index>61</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>567</x>
			<y>105</y>
		</node>
		<node>
			<index>62</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>568</x>
			<y>127</y>
		</node>
		<node>
			<index>63</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>591</x>
			<y>105</y>
		</node>
		<node>
			<index>64</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>592</x>
			<y>128</y>
		</node>
		<node>
			<index>65</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>615</x>
			<y>105</y>
		</node>
		<node>
			<index>66</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>616</x>
			<y>127</y>
		</node>
		<node>
			<index>67</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>640</x>
			<y>105</y>
		</node>
		<node>
			<index>68</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>641</x>
			<y>129</y>
		</node>
		<node>
			<index>69</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>664</x>
			<y>105</y>
		</node>
		<node>
			<index>70</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>664</x>
			<y>128</y>
		</node>
		<node>
			<index>71</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>687</x>
			<y>105</y>
		</node>
		<node>
			<index>72</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>689</x>
			<y>128</y>
		</node>
		<node>
			<index>73</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>167</x>
			<y>360</y>
		</node>
		<node>
			<index>74</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>260</x>
			<y>362</y>
		</node>
	</nodes>
</root>

