<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>10101</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>60</x>
			<y>24</y>
		</node>
		<node>
			<index>10102</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>60</x>
			<y>56</y>
		</node>
		<node>
			<index>10103</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>90</x>
			<y>24</y>
		</node>
		<node>
			<index>10104</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>89</x>
			<y>56</y>
		</node>
		<node>
			<index>10105</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>119</x>
			<y>24</y>
		</node>
		<node>
			<index>10106</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>119</x>
			<y>56</y>
		</node>
		<node>
			<index>10107</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>148</x>
			<y>24</y>
		</node>
		<node>
			<index>10108</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>149</x>
			<y>56</y>
		</node>
		<node>
			<index>10109</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>177</x>
			<y>24</y>
		</node>
		<node>
			<index>10110</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>177</x>
			<y>56</y>
		</node>
		<node>
			<index>10111</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>207</x>
			<y>24</y>
		</node>
		<node>
			<index>10112</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>207</x>
			<y>56</y>
		</node>
		<node>
			<index>10113</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>236</x>
			<y>23</y>
		</node>
		<node>
			<index>10114</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>236</x>
			<y>56</y>
		</node>
		<node>
			<index>10115</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>265</x>
			<y>23</y>
		</node>
		<node>
			<index>10116</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>265</x>
			<y>56</y>
		</node>
		<node>
			<index>10117</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>312</x>
			<y>24</y>
		</node>
		<node>
			<index>10118</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>312</x>
			<y>56</y>
		</node>
		<node>
			<index>10119</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>341</x>
			<y>24</y>
		</node>
		<node>
			<index>10120</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>341</x>
			<y>56</y>
		</node>
		<node>
			<index>10121</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>370</x>
			<y>24</y>
		</node>
		<node>
			<index>10122</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>370</x>
			<y>56</y>
		</node>
		<node>
			<index>10123</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>400</x>
			<y>24</y>
		</node>
		<node>
			<index>10124</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>400</x>
			<y>56</y>
		</node>
		<node>
			<index>10125</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>429</x>
			<y>24</y>
		</node>
		<node>
			<index>10126</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>429</x>
			<y>56</y>
		</node>
		<node>
			<index>10127</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>458</x>
			<y>24</y>
		</node>
		<node>
			<index>10128</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>458</x>
			<y>56</y>
		</node>
		<node>
			<index>10129</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>488</x>
			<y>24</y>
		</node>
		<node>
			<index>10130</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>488</x>
			<y>56</y>
		</node>
		<node>
			<index>10131</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>517</x>
			<y>24</y>
		</node>
		<node>
			<index>10132</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>516</x>
			<y>56</y>
		</node>
		<node>
			<index>10133</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>564</x>
			<y>23</y>
		</node>
		<node>
			<index>10134</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>563</x>
			<y>57</y>
		</node>
		<node>
			<index>10135</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>593</x>
			<y>23</y>
		</node>
		<node>
			<index>10136</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>592</x>
			<y>57</y>
		</node>
		<node>
			<index>10137</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>622</x>
			<y>23</y>
		</node>
		<node>
			<index>10138</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>622</x>
			<y>57</y>
		</node>
		<node>
			<index>10139</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>652</x>
			<y>23</y>
		</node>
		<node>
			<index>10140</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>651</x>
			<y>57</y>
		</node>
		<node>
			<index>10141</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>681</x>
			<y>23</y>
		</node>
		<node>
			<index>10142</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>681</x>
			<y>57</y>
		</node>
		<node>
			<index>10143</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>710</x>
			<y>24</y>
		</node>
		<node>
			<index>10144</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>710</x>
			<y>56</y>
		</node>
		<node>
			<index>10145</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>740</x>
			<y>23</y>
		</node>
		<node>
			<index>10146</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>739</x>
			<y>56</y>
		</node>
		<node>
			<index>10147</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>769</x>
			<y>24</y>
		</node>
		<node>
			<index>10148</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>769</x>
			<y>56</y>
		</node>
		<node>
			<index>10149</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>821</x>
			<y>22</y>
		</node>
		<node>
			<index>10150</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>822</x>
			<y>56</y>
		</node>
		<node>
			<index>10151</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>875</x>
			<y>23</y>
		</node>
		<node>
			<index>10152</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>876</x>
			<y>56</y>
		</node>
	</nodes>
</root>

