<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>4227626</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>49</x>
			<y>69</y>
		</node>
		<node>
			<index>4227634</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>48</x>
			<y>43</y>
		</node>
		<node>
			<index>4227642</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>77</x>
			<y>69</y>
		</node>
		<node>
			<index>4227650</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>76</x>
			<y>43</y>
		</node>
		<node>
			<index>4227658</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>105</x>
			<y>69</y>
		</node>
		<node>
			<index>4227666</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>104</x>
			<y>43</y>
		</node>
		<node>
			<index>4227674</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>133</x>
			<y>69</y>
		</node>
		<node>
			<index>4227682</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>132</x>
			<y>43</y>
		</node>
		<node>
			<index>4227690</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>161</x>
			<y>69</y>
		</node>
		<node>
			<index>4227698</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>160</x>
			<y>43</y>
		</node>
		<node>
			<index>4227706</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>189</x>
			<y>69</y>
		</node>
		<node>
			<index>4227714</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>188</x>
			<y>43</y>
		</node>
		<node>
			<index>4227722</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>217</x>
			<y>69</y>
		</node>
		<node>
			<index>4227730</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>216</x>
			<y>43</y>
		</node>
		<node>
			<index>4227738</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>245</x>
			<y>69</y>
		</node>
		<node>
			<index>4227746</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>244</x>
			<y>43</y>
		</node>
		<node>
			<index>4227754</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>284</x>
			<y>69</y>
		</node>
		<node>
			<index>4227762</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>283</x>
			<y>43</y>
		</node>
		<node>
			<index>4227770</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>312</x>
			<y>69</y>
		</node>
		<node>
			<index>4227778</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>311</x>
			<y>43</y>
		</node>
		<node>
			<index>4227786</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>340</x>
			<y>69</y>
		</node>
		<node>
			<index>4227794</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>339</x>
			<y>43</y>
		</node>
		<node>
			<index>4227802</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>368</x>
			<y>69</y>
		</node>
		<node>
			<index>4227810</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>367</x>
			<y>43</y>
		</node>
		<node>
			<index>4227818</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>396</x>
			<y>69</y>
		</node>
		<node>
			<index>4227826</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>395</x>
			<y>43</y>
		</node>
		<node>
			<index>4227834</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>424</x>
			<y>69</y>
		</node>
		<node>
			<index>4227842</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>423</x>
			<y>43</y>
		</node>
		<node>
			<index>4227850</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>452</x>
			<y>69</y>
		</node>
		<node>
			<index>4227858</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>451</x>
			<y>43</y>
		</node>
		<node>
			<index>4227866</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>480</x>
			<y>69</y>
		</node>
		<node>
			<index>4227874</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>479</x>
			<y>43</y>
		</node>
		<node>
			<index>4227882</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>519</x>
			<y>69</y>
		</node>
		<node>
			<index>4227890</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>518</x>
			<y>43</y>
		</node>
		<node>
			<index>4227898</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>547</x>
			<y>69</y>
		</node>
		<node>
			<index>4227906</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>43</y>
		</node>
		<node>
			<index>4227914</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>575</x>
			<y>69</y>
		</node>
		<node>
			<index>4227922</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>574</x>
			<y>43</y>
		</node>
		<node>
			<index>4227930</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>603</x>
			<y>69</y>
		</node>
		<node>
			<index>4227938</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>602</x>
			<y>43</y>
		</node>
		<node>
			<index>4227946</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>631</x>
			<y>69</y>
		</node>
		<node>
			<index>4227954</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>630</x>
			<y>43</y>
		</node>
		<node>
			<index>4227962</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>659</x>
			<y>69</y>
		</node>
		<node>
			<index>4227970</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>658</x>
			<y>43</y>
		</node>
		<node>
			<index>4227978</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>687</x>
			<y>69</y>
		</node>
		<node>
			<index>4227986</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>686</x>
			<y>43</y>
		</node>
		<node>
			<index>4227994</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>715</x>
			<y>69</y>
		</node>
		<node>
			<index>4228002</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>714</x>
			<y>43</y>
		</node>
		<node>
			<index>4228041</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>767</x>
			<y>81</y>
		</node>
		<node>
			<index>4228049</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>812</x>
			<y>81</y>
		</node>
		<node>
			<index>4228057</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>858</x>
			<y>80</y>
		</node>
		<node>
			<index>4228065</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>903</x>
			<y>80</y>
		</node>
	</nodes>
</root>

