<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>4227626</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>172</x>
			<y>175</y>
		</node>
		<node>
			<index>4227634</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>173</x>
			<y>200</y>
		</node>
		<node>
			<index>4227642</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>548</y>
		</node>
		<node>
			<index>4227650</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>613</y>
		</node>
		<node>
			<index>4227658</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>678</y>
		</node>
		<node>
			<index>4227666</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>743</y>
		</node>
		<node>
			<index>4227674</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>808</y>
		</node>
		<node>
			<index>4227682</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>873</y>
		</node>
		<node>
			<index>4227690</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>938</y>
		</node>
		<node>
			<index>4227698</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1003</y>
		</node>
		<node>
			<index>4227706</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1068</y>
		</node>
		<node>
			<index>4227714</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1133</y>
		</node>
		<node>
			<index>4227722</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1198</y>
		</node>
		<node>
			<index>4227730</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1263</y>
		</node>
		<node>
			<index>4227738</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1328</y>
		</node>
		<node>
			<index>4227746</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1393</y>
		</node>
		<node>
			<index>4227754</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1458</y>
		</node>
		<node>
			<index>4227762</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1523</y>
		</node>
		<node>
			<index>4227770</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1588</y>
		</node>
		<node>
			<index>4227778</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1653</y>
		</node>
		<node>
			<index>4227786</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1718</y>
		</node>
		<node>
			<index>4227794</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1783</y>
		</node>
		<node>
			<index>4227802</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1848</y>
		</node>
		<node>
			<index>4227810</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1913</y>
		</node>
		<node>
			<index>4227818</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>1978</y>
		</node>
		<node>
			<index>4227826</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2043</y>
		</node>
		<node>
			<index>4227834</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2108</y>
		</node>
		<node>
			<index>4227842</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2173</y>
		</node>
		<node>
			<index>4227850</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2238</y>
		</node>
		<node>
			<index>4227858</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2303</y>
		</node>
		<node>
			<index>4227866</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2368</y>
		</node>
		<node>
			<index>4227874</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2433</y>
		</node>
		<node>
			<index>4227882</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2498</y>
		</node>
		<node>
			<index>4227890</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2563</y>
		</node>
		<node>
			<index>4227898</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2628</y>
		</node>
		<node>
			<index>4227906</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2693</y>
		</node>
		<node>
			<index>4227914</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2758</y>
		</node>
		<node>
			<index>4227922</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2823</y>
		</node>
		<node>
			<index>4227930</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2888</y>
		</node>
		<node>
			<index>4227938</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>2953</y>
		</node>
		<node>
			<index>4227946</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3018</y>
		</node>
		<node>
			<index>4227954</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3083</y>
		</node>
		<node>
			<index>4227962</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3148</y>
		</node>
		<node>
			<index>4227970</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3213</y>
		</node>
		<node>
			<index>4227978</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3278</y>
		</node>
		<node>
			<index>4227986</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3343</y>
		</node>
		<node>
			<index>4227994</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3408</y>
		</node>
		<node>
			<index>4228002</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3473</y>
		</node>
		<node>
			<index>4228041</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3538</y>
		</node>
		<node>
			<index>4228049</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3603</y>
		</node>
		<node>
			<index>4228057</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3668</y>
		</node>
		<node>
			<index>4228065</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>0</x>
			<y>3733</y>
		</node>
	</nodes>
</root>

