<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>201</x>
			<y>34</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>316</x>
			<y>33</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>182</x>
			<y>204</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>270</x>
			<y>205</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>357</x>
			<y>205</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>444</x>
			<y>205</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>534</x>
			<y>205</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>622</x>
			<y>205</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>132</x>
			<y>348</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>133</x>
			<y>371</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>157</x>
			<y>348</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>158</x>
			<y>371</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>181</x>
			<y>347</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>181</x>
			<y>372</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>204</x>
			<y>347</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>204</x>
			<y>371</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>227</x>
			<y>347</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>228</x>
			<y>371</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>251</x>
			<y>348</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>252</x>
			<y>372</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>277</x>
			<y>347</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>278</x>
			<y>372</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>302</x>
			<y>347</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>302</x>
			<y>372</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>326</x>
			<y>347</y>
		</node>
		<node>
			<index>27</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>326</x>
			<y>371</y>
		</node>
		<node>
			<index>28</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>349</x>
			<y>347</y>
		</node>
		<node>
			<index>29</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>350</x>
			<y>372</y>
		</node>
		<node>
			<index>30</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>373</x>
			<y>348</y>
		</node>
		<node>
			<index>31</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>373</x>
			<y>372</y>
		</node>
		<node>
			<index>32</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>397</x>
			<y>348</y>
		</node>
		<node>
			<index>33</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>398</x>
			<y>372</y>
		</node>
		<node>
			<index>34</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>422</x>
			<y>347</y>
		</node>
		<node>
			<index>35</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>422</x>
			<y>372</y>
		</node>
		<node>
			<index>36</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>445</x>
			<y>347</y>
		</node>
		<node>
			<index>37</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>446</x>
			<y>371</y>
		</node>
		<node>
			<index>38</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>469</x>
			<y>347</y>
		</node>
		<node>
			<index>39</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>469</x>
			<y>371</y>
		</node>
		<node>
			<index>40</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>494</x>
			<y>347</y>
		</node>
		<node>
			<index>41</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>494</x>
			<y>370</y>
		</node>
		<node>
			<index>42</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>517</x>
			<y>347</y>
		</node>
		<node>
			<index>43</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>517</x>
			<y>370</y>
		</node>
		<node>
			<index>44</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>543</x>
			<y>347</y>
		</node>
		<node>
			<index>45</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>543</x>
			<y>371</y>
		</node>
		<node>
			<index>46</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>568</x>
			<y>348</y>
		</node>
		<node>
			<index>47</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>569</x>
			<y>371</y>
		</node>
		<node>
			<index>48</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>593</x>
			<y>348</y>
		</node>
		<node>
			<index>49</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>592</x>
			<y>370</y>
		</node>
		<node>
			<index>50</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>616</x>
			<y>348</y>
		</node>
		<node>
			<index>51</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>616</x>
			<y>371</y>
		</node>
		<node>
			<index>52</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>639</x>
			<y>347</y>
		</node>
		<node>
			<index>53</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>639</x>
			<y>371</y>
		</node>
		<node>
			<index>54</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>664</x>
			<y>347</y>
		</node>
		<node>
			<index>55</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>664</x>
			<y>371</y>
		</node>
		<node>
			<index>56</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>688</x>
			<y>347</y>
		</node>
		<node>
			<index>57</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>688</x>
			<y>371</y>
		</node>
	</nodes>
</root>

