<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>95</x>
			<y>24</y>
		</node>
		<node>
			<index>2</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>95</x>
			<y>46</y>
		</node>
		<node>
			<index>3</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>120</x>
			<y>24</y>
		</node>
		<node>
			<index>4</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>120</x>
			<y>46</y>
		</node>
		<node>
			<index>5</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>145</x>
			<y>24</y>
		</node>
		<node>
			<index>6</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>145</x>
			<y>46</y>
		</node>
		<node>
			<index>7</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>170</x>
			<y>24</y>
		</node>
		<node>
			<index>8</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>170</x>
			<y>46</y>
		</node>
		<node>
			<index>9</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>195</x>
			<y>24</y>
		</node>
		<node>
			<index>10</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>195</x>
			<y>45</y>
		</node>
		<node>
			<index>11</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>219</x>
			<y>24</y>
		</node>
		<node>
			<index>12</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>219</x>
			<y>46</y>
		</node>
		<node>
			<index>13</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>244</x>
			<y>24</y>
		</node>
		<node>
			<index>14</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>244</x>
			<y>45</y>
		</node>
		<node>
			<index>15</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>269</x>
			<y>24</y>
		</node>
		<node>
			<index>16</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>269</x>
			<y>45</y>
		</node>
		<node>
			<index>17</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>301</x>
			<y>23</y>
		</node>
		<node>
			<index>18</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>301</x>
			<y>45</y>
		</node>
		<node>
			<index>19</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>325</x>
			<y>23</y>
		</node>
		<node>
			<index>20</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>325</x>
			<y>45</y>
		</node>
		<node>
			<index>21</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>350</x>
			<y>24</y>
		</node>
		<node>
			<index>22</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>350</x>
			<y>46</y>
		</node>
		<node>
			<index>23</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>375</x>
			<y>23</y>
		</node>
		<node>
			<index>24</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>375</x>
			<y>44</y>
		</node>
		<node>
			<index>25</index>
			<img>image/up_green.gif</img>
			<direction>1</direction>
			<x>400</x>
			<y>23</y>
		</node>
		<node>
			<index>26</index>
			<img>image/up_green.gif</img>
			<direction>2</direction>
			<x>400</x>
			<y>45</y>
		</node>
	</nodes>
</root>

