// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.afunms.rmi.service;

public final class RMIClientImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.afunms.rmi.service.RMIClient, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_sendMessage_0;
    
    static {
	try {
	    $method_sendMessage_0 = com.afunms.rmi.service.RMIClient.class.getMethod("sendMessage", new java.lang.Class[] {com.afunms.rmi.service.RMIClientAction.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RMIClientImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of sendMessage(RMIClientAction)
    public com.afunms.rmi.service.RMIAttribute sendMessage(com.afunms.rmi.service.RMIClientAction $param_RMIClientAction_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sendMessage_0, new java.lang.Object[] {$param_RMIClientAction_1}, 6589549358291981965L);
	    return ((com.afunms.rmi.service.RMIAttribute) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
